### PR TITLE
Upgrade openssl / migrate to SMIME signing

### PR DESCRIPTION
**Pull request by patroqueeet**
tests are passing, sry for the commit mess.

will resolve

```
/home/darg/darg/.ve/lib/python3.8/site-packages/django_walletpass/crypto.py:61: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  cert._x509,
```

### CODE REVIEW

**Comment by alexandernst** [comment]
Hi! Can you revert the double quotes and the new lines that you added, please? 🙏 (keep the style / indent of the original code)

**Comment by patroqueeet** [comment]
> Hi! Can you revert the double quotes and the new lines that you added, please? 🙏 (keep the style / indent of the original code)

hey, that is automatically `isort`ed and `black`ed formatting. I believe this is somehow now considered python best practice. But I can revert those, if you quickly confirm.

**Comment by alexandernst** [comment]
Yes, please. We keep styling / indent the same way in all the org's projects 🙏

**Comment by patroqueeet** [comment]
✅  - tests passing.

**Review by NachE — APPROVED** [review]

**Review by NachE — APPROVED** [review]

**Comment by alexandernst** [comment]
The newly released version: https://pypi.org/project/django-walletpass/2.0/

❤️

**Pull request merged**
